import {
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_TITLE,
} from '@/constants/navigation.constant'
import { ADMIN, USER } from '@/constants/roles.constant'

const rootNavigationConfig = [
    {
        key: 'root',
        path: '',
        title: 'root',
        translateKey: 'root',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        meta: {
            horizontalMenu: {
                layout: 'default',
            },
        },
        subMenu: [
            {
                key: 'home',
                path: `/home`,
                title: 'Trang chủ',
                translateKey: 'Home',
                icon: 'home',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'user',
                path: '',
                title: 'Người dùng',
                translateKey: 'user',
                icon: 'user',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                meta: {
                    description: {
                        translateKey: 'user',
                        label: 'user',
                    },
                },
                subMenu: [
                    {
                        key: 'departments',
                        path: `/admin/user/departments`,
                        title: 'Phòng ban',
                        translateKey: 'departments',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'user-announcements',
                path: '',
                title: 'Thông báo',
                translateKey: 'announcements',
                icon: 'announce',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [USER],
                meta: {
                    description: {
                        translateKey: 'announcements',
                        label: 'announcements',
                    },
                },
                subMenu: [
                    {
                        key: 'private',
                        path: `/announcements/private`,
                        title: 'Thông báo nội bộ',
                        translateKey: 'announcements-private',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [USER],
                        subMenu: [],
                    },
                    {
                        key: 'public',
                        path: `/announcements/public`,
                        title: 'Thông báo công khai',
                        translateKey: 'announcements-public',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'news',
                path: '',
                title: 'Tin tức',
                translateKey: 'news',
                icon: 'news',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                meta: {
                    description: {
                        translateKey: 'news',
                        label: 'news',
                    },
                },
                subMenu: [
                    {
                        key: 'news',
                        path: `/admin/news`,
                        title: 'Danh sách tin tức',
                        translateKey: 'news-list',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'news-categories',
                        path: `/admin/news/categories`,
                        title: 'Danh mục tin tức',
                        translateKey: 'news-categories',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'news-tags',
                        path: `/admin/news/tags`,
                        title: 'Danh sách tags',
                        translateKey: 'news-tags',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'announcements',
                path: '',
                title: 'Thông báo',
                translateKey: 'announcements',
                icon: 'announce',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                meta: {
                    description: {
                        translateKey: 'announcements',
                        label: 'announcements',
                    },
                },
                subMenu: [
                    {
                        key: 'announcements',
                        path: `/admin/announcements`,
                        title: 'Danh sách thông báo',
                        translateKey: 'announcements-list',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'announcements-categories',
                        path: `/admin/announcements/categories`,
                        title: 'Danh mục thông báo',
                        translateKey: 'announcements-categories',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'violations',
                path: '',
                title: 'Quản lý vi phạm',
                translateKey: 'violations',
                icon: 'violations',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                meta: {
                    description: {
                        translateKey: 'violations',
                        label: 'violations',
                    },
                },
                subMenu: [
                    {
                        key: 'violations',
                        path: `/admin/violations`,
                        title: 'Danh sách vi phạm',
                        translateKey: 'violations-list',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'history',
                        path: `/admin/violations/history`,
                        title: 'Lịch sử xử lý vi phạm',
                        translateKey: 'violations-history',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'list-violators',
                        path: `/admin/violations/list-violators`,
                        title: 'Đối tượng vi phạm',
                        translateKey: 'violations-history',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'violation-types',
                        path: `/admin/violations/violation-types`,
                        title: 'Loại vi phạm',
                        translateKey: 'violation-types',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'waterways',
                        path: `/admin/violations/waterways`,
                        title: 'Tuyến kênh',
                        translateKey: 'waterways',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                ],
            },
        ],
    },
]

export default rootNavigationConfig
