import { CiCalendarDate, CiFileOn, CiWarning } from 'react-icons/ci'
import { FaRegUser } from 'react-icons/fa'
import { FaClipboardUser } from 'react-icons/fa6'
import { GoBell, GoHome } from 'react-icons/go'
import { ImUserTie } from 'react-icons/im'
import {
    PiBoneDuotone,
    PiBookDuotone,
    PiBreadDuotone,
    PiBrowsersDuotone,
    PiCalendarCheckDuotone,
    PiCalendarDuotone,
    PiCardsDuotone,
    PiCaretCircleDownDuotone,
    PiChalkboardSimpleDuotone,
    PiChartBarDuotone,
    PiChartDonutDuotone,
    PiChartLineUpDuotone,
    PiChartPieSliceDuotone,
    PiChatCenteredDotsDuotone,
    PiChatCenteredDuotone,
    PiChatCircleDuotone,
    PiChatDotsDuotone,
    PiCheckSquareDuotone,
    PiCircleHalfTiltDuotone,
    PiClipboardTextDuotone,
    PiClockAfternoonDuotone,
    PiClockCountdownDuotone,
    PiCodeDuotone,
    PiCodeSimpleDuotone,
    PiCompassDuotone,
    PiCurrencyCircleDollarDuotone,
    PiCursorClickDuotone,
    PiDesktopDuotone,
    PiDotsThreeCircleDuotone,
    PiEnvelopeDuotone,
    PiFileMagnifyingGlassDuotone,
    PiFileTextDuotone,
    PiFilmScriptDuotone,
    PiFolderOpenDuotone,
    PiFootprintsDuotone,
    PiGearDuotone,
    PiGridFourDuotone,
    PiHandWithdrawDuotone,
    PiHeadsetDuotone,
    PiHouseLineDuotone,
    PiImagesDuotone,
    PiKeyDuotone,
    PiKeyholeDuotone,
    PiLightbulbDuotone,
    PiListChecksBold,
    PiListChecksDuotone,
    PiListDuotone,
    PiListMagnifyingGlassDuotone,
    PiListPlusDuotone,
    PiListStarDuotone,
    PiLockKeyOpenDuotone,
    PiMapTrifoldDuotone,
    PiMedalDuotone,
    PiMegaphoneDuotone,
    PiNewspaperDuotone,
    PiNewspaperThin,
    PiNotePencilDuotone,
    PiPackageDuotone,
    PiPasswordDuotone,
    PiPencilSimpleLineDuotone,
    PiPlusSquareDuotone,
    PiProjectorScreenChartDuotone,
    PiPuzzlePieceDuotone,
    PiQuestionDuotone,
    PiQuotesDuotone,
    PiRadioButtonDuotone,
    PiRocketDuotone,
    PiRowsDuotone,
    PiRowsPlusBottomDuotone,
    PiShareNetworkDuotone,
    PiShieldCheckDuotone,
    PiShoppingCartDuotone,
    PiShoppingCartSimpleDuotone,
    PiSparkleDuotone,
    PiSpeedometerDuotone,
    PiSpinnerBallDuotone,
    PiSpinnerGapDuotone,
    PiStackPlusDuotone,
    PiSwatchesDuotone,
    PiTableDuotone,
    PiTagDuotone,
    PiTextAaDuotone,
    PiTextIndentDuotone,
    PiToggleRightDuotone,
    PiToolboxDuotone,
    PiUploadDuotone,
    PiUserCircleDuotone,
    PiUserGearDuotone,
    PiUserListDuotone,
    PiUserPlusDuotone,
    PiUsersDuotone,
    PiWarningDuotone,
} from 'react-icons/pi'

const navigationIcon = {
    uiComponents: <PiPuzzlePieceDuotone />,
    common: <PiSwatchesDuotone />,
    uiCommonButton: <PiCursorClickDuotone />,
    uiCommonGrid: <PiGridFourDuotone />,
    uiCommonTypography: <PiTextAaDuotone />,
    uiCommonIcons: <PiImagesDuotone />,
    feedback: <PiChatDotsDuotone />,
    uiFeedbackAlert: <PiWarningDuotone />,
    uiFeedbackDialog: <PiChatCircleDuotone />,
    uiFeedbackDrawer: <PiHandWithdrawDuotone />,
    uiFeedbackProgress: <PiSpinnerGapDuotone />,
    uiFeedbackSkeleton: <PiBoneDuotone />,
    uiFeedbackSpinner: <PiSpinnerBallDuotone />,
    uiFeedbackToast: <PiBreadDuotone />,
    dataDisplay: <PiDesktopDuotone />,
    uiDataDisplayAvatar: <PiUserCircleDuotone />,
    uiDataDisplayBadge: <PiMedalDuotone />,
    uiDataDisplayCalendar: <PiCalendarDuotone />,
    uiDataDisplayCard: <PiCardsDuotone />,
    uiDataDisplayTable: <PiTableDuotone />,
    uiDataDisplayTag: <PiTagDuotone />,
    uiDataDisplayTimeline: <PiClockCountdownDuotone />,
    uiDataDisplayTooltip: <PiChatCenteredDuotone />,
    forms: <PiFileTextDuotone />,
    uiFormsCheckbox: <PiCheckSquareDuotone />,
    uiFormsDatepicker: <PiCalendarCheckDuotone />,
    uiFormsFormControl: <PiClipboardTextDuotone />,
    uiFormsInput: <PiRowsDuotone />,
    uiFormsInputGroup: <PiRowsPlusBottomDuotone />,
    uiFormsRadio: <PiRadioButtonDuotone />,
    uiFormsSegment: <PiChartDonutDuotone />,
    uiFormsSelect: <PiListChecksBold />,
    uiFormsSwitcher: <PiToggleRightDuotone />,
    uiFormsTimePicker: <PiClockAfternoonDuotone />,
    uiFormsUpload: <PiUploadDuotone />,
    navigation: <PiCompassDuotone />,
    uiNavigationDropdown: <PiCaretCircleDownDuotone />,
    uiNavigationMenu: <PiListDuotone />,
    uiNavigationPagination: <PiCodeSimpleDuotone />,
    uiNavigationSteps: <PiFootprintsDuotone />,
    uiNavigationTabs: <PiBrowsersDuotone />,
    graph: <PiChartPieSliceDuotone />,
    uiGraphChart: <PiChartLineUpDuotone />,
    uiGraphMaps: <PiMapTrifoldDuotone />,
    concepts: <PiLightbulbDuotone />,
    customers: <PiUsersDuotone />,
    customerList: <PiUserListDuotone />,
    customerEdit: <PiPencilSimpleLineDuotone />,
    customerCreate: <PiUserPlusDuotone />,
    customerDetails: <PiUserCircleDuotone />,
    products: <PiPackageDuotone />,
    productList: <PiListStarDuotone />,
    productEdit: <PiNotePencilDuotone />,
    productCreate: <PiPlusSquareDuotone />,
    projects: <PiProjectorScreenChartDuotone />,
    projectScrumBoard: <PiChalkboardSimpleDuotone />,
    projectList: <PiListChecksDuotone />,
    projectDetails: <PiFileMagnifyingGlassDuotone />,
    projectTask: <PiCalendarCheckDuotone />,
    projectIssue: <PiWarningDuotone />,
    orders: <PiShoppingCartDuotone />,
    orderList: <PiListPlusDuotone />,
    orderEdit: <PiFilmScriptDuotone />,
    ordeDetails: <PiListMagnifyingGlassDuotone />,
    orderCreate: <PiStackPlusDuotone />,
    calendar: <PiCalendarDuotone />,
    fileManager: <PiFolderOpenDuotone />,
    mail: <PiEnvelopeDuotone />,
    account: <PiUserCircleDuotone />,
    accountSettings: <PiGearDuotone />,
    accountActivityLogs: <PiFileTextDuotone />,
    accountRoleAndPermission: <PiUserGearDuotone />,
    accountPricing: <PiCurrencyCircleDollarDuotone />,
    ai: <PiSparkleDuotone />,
    aiChat: <PiChatCenteredDotsDuotone />,
    aiImage: <PiImagesDuotone />,
    chat: <PiChatCircleDuotone />,
    helpCenter: <PiQuestionDuotone />,
    helpCeterSupportHub: <PiHeadsetDuotone />,
    helpCeterArticle: <PiNewspaperDuotone />,
    helpCeterEditArticle: <PiTextIndentDuotone />,
    helpCeterManageArticle: <PiQuotesDuotone />,
    authentication: <PiShieldCheckDuotone />,
    signIn: <PiKeyDuotone />,
    signUp: <PiUserPlusDuotone />,
    forgotPassword: <PiLockKeyOpenDuotone />,
    resetPassword: <PiKeyholeDuotone />,
    otpVerification: <PiPasswordDuotone />,
    dashboard: <PiSpeedometerDuotone />,
    dashboardEcommerce: <PiShoppingCartSimpleDuotone />,
    dashboardProject: <PiRocketDuotone />,
    dashboardAnalytic: <PiChartBarDuotone />,
    dashboardMarketing: <PiMegaphoneDuotone />,
    others: <PiDotsThreeCircleDuotone />,
    accessDenied: <PiCircleHalfTiltDuotone />,
    landing: <PiHouseLineDuotone />,
    documentation: <PiBookDuotone />,
    sharedComponentDoc: <PiShareNetworkDuotone />,
    utilsDoc: <PiToolboxDuotone />,
    changeLog: <PiCodeDuotone />,
    home: <GoHome />,
    announce: <GoBell />,
    user: <FaRegUser />,
    violations: <CiWarning />,
    file: <CiFileOn />,
    news: <PiNewspaperThin />,
    documents: <PiFileTextDuotone />,
    schedules: <CiCalendarDate />,
    positions: <FaClipboardUser />,
    employees: <ImUserTie />,
}

export default navigationIcon
